---
title: Daryl Shaw
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
url: https://darylshaw.co.uk
permalink: pretty
google_analytics: UA-54371675-1
name: Daryl Shaw
email: daryl@darylshaw.co.uk
twitter:
  username: daryl_shaw
markdown: kramdown
redcarpet:
  extensions:
  - autolink
  - fenced_code_blocks
  - lax_spacing
  - strikethrough
  - superscript
  - tables
  - footnotes
  - highlight
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-feed
repository: daryl-shaw/darylshaw.co.uk
