---
title: Daryl Shaw
url: http://darylshaw.co.uk
timezone: UTC
permalink: pretty
google_analytics: UA-54371675-1
name: Daryl Shaw
email: daryl@darylshaw.co.uk
twitter: daryl_shaw
collections:
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
markdown: kramdown
redcarpet:
  extensions:
  - autolink
  - fenced_code_blocks
  - lax_spacing
  - strikethrough
  - superscript
  - tables
  - footnotes
  - highlight
sass:
    sass_dir: _sass
    style: compressed
