---
title: Daryl Shaw
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  blog_tags:
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: blog_tags
  values:
    layout: tag
url: https://darylshaw.co.uk
permalink: pretty
fathom_analytics: JNJBHQAI
name: Daryl Shaw
email: daryl@darylshaw.co.uk
twitter:
  username: daryl_shaw
markdown: kramdown
redcarpet:
  extensions:
  - autolink
  - fenced_code_blocks
  - lax_spacing
  - strikethrough
  - superscript
  - tables
  - footnotes
  - highlight
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from
repository: darylshaw/darylshaw.co.uk
