---
title: Daryl Shaw
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  blog_tags:
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
  notes:
    title: Notes
    output: true
defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    permalink: "/blog/:title/"
-
  scope:
    path: ""
    type: "blog_tags"
  values:
    layout: "tag"
-
  scope:
    path: ""
    type: "notes"
  values:
    permalink: "/:collection/:title"
url: https://darylshaw.co.uk
permalink: pretty
fathom_analytics: JNJBHQAI
name: Daryl Shaw
email: daryl@darylshaw.co.uk
twitter:
  username: daryl_shaw
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from
repository: darylshaw/darylshaw.co.uk
feed:
  collections:
  - notes
