# Specific branch context: all deploys from this specific branch will inherit
# these settings.
[context.staging] # 'staging' is a branch name
  command = "JEKYLL_ENV=staging jekyll build --config _config.yml,_config_staging.yml"
